# <img src="https://i0.wp.com/tech-mags.com/wp-content/uploads/2022/03/1200px-NumPy_logo_2020.svg_.png?resize=1024%2C461&ssl=1" /> 

# Introduction to NumPy

**NumPy** is short for "Numerical Python" and is a powerful library that provides a broad array of functionality for performing fast numerical and mathematical operations in Python.


## Key Features of NumPy:
- **NumPy**'s core data structure is the **ndArray** (or n-dimensional array).
- Much of the functionality of **NumPy** is written in the **C** programming language behind the scenes to optimize performance.
- **NumPy** is used in other popular Python packages like **Pandas**, **Matplotlib**, and **scikit-learn**.


## A First Look at NumPy Arrays:
At first glance, a **NumPy array** might look similar to a **List** (or in the case of multi-dimensional arrays, a List of Lists...). However, there are significant differences that make **NumPy arrays** faster and more efficient for numerical computations.


### Lists vs NumPy Arrays:
- **Lists** can hold different data types (integers, strings, etc.), which can limit performance when performing mathematical operations.
- **NumPy arrays** are homogeneous, meaning all values in the array are of the same type. This uniformity allows **NumPy** to perform calculations much faster and more efficiently.

---

**NumPy** serves as the foundation for many advanced computational tasks in **Python**, including data analysis, machine learning, and artificial intelligence.


###  Installing NumPy

In [14]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


DEPRECATION: Loading egg at g:\anaconda\lib\site-packages\huggingface_hub-0.24.6-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330


In [2]:
# import library
import numpy as np
import pandas as pd

In [10]:
from numpy import *

In [20]:
#  Creating a 1-D list
list1 = [12, 3, 45, 4, 6]

In [21]:
list1

[12, 3, 45, 4, 6]

In [22]:
#  Creating a 1-D array
a = np.array(list1)
a

array([12,  3, 45,  4,  6])

In [13]:
# Creating a 2-D list
list2d = [[1, 2, 3], [4, 5, 6]]
list2d

[[1, 2, 3], [4, 5, 6]]

In [16]:
# Creating a 2-D array
b = np.array(list2d)
b

array([[1, 2, 3],
       [4, 5, 6]])

 NumPy provides us the ability to do so much more than we
 could do with Lists, and at a much, much faster speed!


In [5]:
# Creating an array filled with zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

 - `np.zeros`
# <img src="https://www.w3resource.com/w3r_images/numpy-array-zeros-function-image-a.png" /> 

In [17]:
# Creating an array filled with ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

 - `np.eye`
# <img src="https://www.w3resource.com/w3r_images/numpy-array-eye-function-image-1.png" /> 

In [19]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [20]:
np.eye(4, k=1, dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [21]:
e = np.full(4, 10)
e

array([10, 10, 10, 10])

In [22]:
e = np.full((2, 2), 7)
e

array([[7, 7],
       [7, 7]])

- **`np.empty`**: Creates a new array without initializing its entries. The values in the array are whatever happens to already exist at that memory location.

In [23]:
np.empty(4)

array([1., 1., 1., 1.])


- **The `np.diag` function** returns the diagonal elements of the array, or it can create a diagonal matrix from a 1D array.

- **The `np.count_nonzero` function** returns the number of non-zero elements in the array.


In [24]:
arr = np.array([2, 8, 2, 4])
arr

array([2, 8, 2, 4])

In [25]:
 diag_arr = diag(arr)
 diag_arr

array([[2, 0, 0, 0],
       [0, 8, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

In [26]:
count_nonzero(diag_arr)

4

In [27]:
np.count_nonzero(diag_arr == 0)

12

- **The `type` function** returns the type of the array.


In [28]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
type(b)

numpy.ndarray



- **The `shape` function** returns the shape of the array.


In [30]:
b.shape

(2, 3)


- **The `len` function** returns the size of the array.


In [31]:
len(b)

2



- **The `ndim` function** returns the number of dimensions of the array.


In [32]:
ndim(b)

2

The difference between using len() and ndim in NumPy

In [33]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(len(arr_2d))

arr_1d = np.array([1, 2, 3, 4, 5])
print(len(arr_1d))


3
5


In [34]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d.ndim)

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim)

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d.ndim)


2
1
3



- **The `size` function** returns the size of the array.

In [35]:
b.size

6

- **`np.unique(k)`** returns the unique elements in the array.
- **`np.unique(k, return_index=True)`** returns both the unique elements and their indices in the original array.

In [36]:
k = np.array([1, 2, 3, 1, 4, 2])
x = np.unique(k)
print(x) 

[1 2 3 4]


In [37]:
import numpy as np

k = np.array([1, 2, 3, 1, 4, 2])
unique_values, indices = np.unique(k, return_index=True)
print("Unique values:", unique_values) 
print("Indices of unique values:", indices)  


Unique values: [1 2 3 4]
Indices of unique values: [0 1 2 4]


 **`np.delete()`** function is used to remove elements from an array. You can specify the index (or indices) of the elements you want to delete.

In [38]:
arr = np.array([10, 20, 30, 40])

# Delete element 20 (at index 1)
d = np.delete(arr, 1)
print(d)  


[10 30 40]




- **`np.linspace`**: Returns an array of evenly spaced values over a specified range, where you can define the number of points.


In [2]:
arr = np.linspace(0, 1, 5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
arr = np.linspace(0, 20, 5)
arr

array([ 0.,  5., 10., 15., 20.])

In [8]:
np.linspace(1, 30, num=5, retstep=True)

(array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ]), 7.25)

- **`np.arange`**: Returns an array with evenly spaced values within a specified range.


In [41]:
arr = np.arange(0, 10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr = np.arange(0, 100, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [43]:
arr[0:7]

array([ 0,  2,  4,  6,  8, 10, 12])


- **`np.random.random`**: Returns an array of random float numbers between 0 and 1 with a specified shape.


In [44]:
arr = np.random.random(2)
arr

array([0.83132899, 0.62244802])

In [45]:
np.random.random((3, 4))

array([[0.5149957 , 0.89072198, 0.63850039, 0.39302396],
       [0.38450142, 0.17935874, 0.17906248, 0.76745543],
       [0.14021109, 0.99098683, 0.43920458, 0.05044245]])

In [46]:
np.random.random(1, 50, 6)

TypeError: random() takes at most 1 positional argument (3 given)


- **`np.random.randint`**: Generates an array of random integers within a specified range, with a defined shape.


In [47]:
arr = np.random.randint(0, 10)
arr

7

In [48]:
arr = np.random.randint(0, 10, 6)
arr

array([4, 8, 8, 1, 3, 4])

In [49]:
np.random.randint(1, 100, size=(3, 6))
# 3 is num of row
#  6 num of col

array([[47, 16, 60, 36, 77, 96],
       [20, 65, 34,  2, 65, 34],
       [60, 81, 24, 32, 45, 42]])

In [50]:
np.random.randint(1, 100, size=(3, 6, 4))
#  3 is num matreix
#  6 is n rows and 4 is n cols

array([[[50, 47, 71, 18],
        [16, 55,  7, 19],
        [47, 13, 71, 94],
        [ 1, 28, 72, 77],
        [77, 71, 12, 38],
        [34, 26, 86,  5]],

       [[22, 20, 86, 46],
        [58, 91, 89, 41],
        [13, 61,  6, 53],
        [20, 73, 23, 64],
        [48, 41, 97, 25],
        [94, 48, 86, 98]],

       [[63, 20, 93, 30],
        [40, 42, 41, 86],
        [13, 80, 95, 74],
        [78, 56, 46, 85],
        [77, 17, 16, 58],
        [60, 29, 56, 85]]])


- **`np.random.rand()`**: Returns a random float number between 0 and 1.

The `rand()` function generates random numbers from a uniform distribution over the interval [0, 1). You can specify the shape of the output array.

In [51]:
np.random.rand()

0.7407834850919429

In [52]:
np.random.rand(15)

array([0.95697019, 0.67825021, 0.64047113, 0.01688786, 0.57134385,
       0.57272712, 0.0767637 , 0.13810313, 0.80279171, 0.30048646,
       0.76192702, 0.45702715, 0.69292646, 0.33026299, 0.25773429])

In [53]:
np.random.rand(6, 2)

array([[0.30561439, 0.2970974 ],
       [0.43777276, 0.66151346],
       [0.92556491, 0.807772  ],
       [0.56131113, 0.32536229],
       [0.00385748, 0.06905026],
       [0.80386826, 0.31321035]])

In [54]:
np.random.rand(4, 6, 2)

array([[[0.52100952, 0.08234169],
        [0.96127324, 0.51175863],
        [0.62014095, 0.71109284],
        [0.37563643, 0.7466189 ],
        [0.64912717, 0.66498203],
        [0.92087481, 0.19520187]],

       [[0.00645547, 0.94479499],
        [0.25004584, 0.51708205],
        [0.0715918 , 0.50638825],
        [0.08494928, 0.8363789 ],
        [0.67744791, 0.43680427],
        [0.28845098, 0.50335823]],

       [[0.94243431, 0.01012649],
        [0.69730536, 0.08729183],
        [0.25825253, 0.57532119],
        [0.55700506, 0.13917815],
        [0.14232493, 0.1262439 ],
        [0.32428943, 0.08465649]],

       [[0.15927355, 0.24332263],
        [0.25126754, 0.0811254 ],
        [0.32427468, 0.33347819],
        [0.32639264, 0.42894158],
        [0.72406334, 0.4802626 ],
        [0.15647443, 0.41432929]]])

- **`np.random.uniform`**: Generates random numbers using a uniform distribution between the low and high values, and always returns floating-point numbers (float).

In [3]:
np.random.uniform()

0.5457159114636012

In [5]:
np.random.uniform(1, 100)

81.32906061683013

In [6]:
np.random.uniform(1, 100, 3)

array([ 4.4371207 , 84.67306318, 55.63143783])

In [7]:
np.random.uniform((3, 10))

array([1.66278246, 8.56786679])

In [8]:
np.random.uniform(1, 100, (3, 3))

array([[94.65108787, 42.20047143,  4.03512953],
       [61.66822388, 11.45474802, 31.91095033],
       [70.82868548, 35.06059775, 53.20833247]])


- **`np.max`**: Returns the maximum value in an array.

- **`np.min`**: Returns the minimum value in an array.

- **`np.mean`**: Calculates the average of the values in the array.

- **`np.sum`**: Returns the sum of all elements in the array.

- **`np.std`**: Calculates the standard deviation of the values in the array.

# <img src="https://numpy.org/devdocs/_images/np_matrix_aggregation.png" /> 

**` Max, Min, Mean, Sum, Standard Deviation of a 1D array`**

In [60]:
array_1d = np.random.randint(0, 10, 7)
array_1d

array([8, 3, 2, 7, 4, 5, 7])

In [61]:
array_1d.max()

8

In [62]:
array_1d.min()

2

In [63]:
array_1d.mean()

5.142857142857143

In [64]:
array_1d.sum()

36

In [65]:
array_1d.std()

2.0995626366712954

**` Max, Min, Mean, Sum, Standard Deviation of a 2D array`**

In [66]:
array_2d = np.random.randint(0, 10, (2, 3))
array_2d

array([[6, 4, 3],
       [5, 8, 3]])

In [67]:
array_2d.max()
# Output: 9

array_2d.max(axis=0)
# axis=0 means column wise
# Output: array([9, 8, 7])

array_2d.max(axis=1)
# axis=1 means row wise
# Output: array([7, 9, 8])

array_2d.min(axis=0)
# Output: array([1, 2, 3])

array_2d.min(axis=1)
# Output: array([1, 3, 2])

array_2d.mean(axis=0)
# Output: array([5., 5., 5.])

array_2d.mean(axis=1)
# Output: array([4., 6., 5.])

array_2d.sum(axis=0)
# Output: array([15, 15, 15])

array_2d.sum(axis=1)
# Output: array([10, 18, 15])

array([13, 16])


- **`argmax()`**: Returns the index of the maximum value in the array .

- **`argmin()`**: Returns the index of the minimum value in the array .


In [68]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
b.argmax()

5

In [70]:
b.argmin()

0

- **Arithmetic operations on a 1D array**

# <img src="https://numpy.org/devdocs/_images/np_sub_mult_divide.png" />


In [71]:
a = np.array([1, 2, 3, 4, 5])

a + 10
# Output: array([11, 12, 13, 14, 15])
a - 10
# Output: array([-9, -8, -7, -6, -5])
a * 10
# Output: array([10, 20, 30, 40, 50])
a / 10
# Output: array([0.1, 0.2, 0.3, 0.4, 0.5])
a**2
# Output: array([ 1,  4,  9, 16, 25])
a % 2
# Output: array([1, 0, 1, 0, 1])
a // 2
# Output: array([0, 1, 1, 2, 2])

array([0, 1, 1, 2, 2], dtype=int32)

- **Mathematical operations on a 1D array**

In [72]:
a = np.array([-2, -1, 0, 1, 2])

np.square(a)
# Output: array([4, 1, 0, 1, 4])
np.sqrt(a)
# Output: array([nan, nan, 0. , 1. , 1.41421356])
np.sin(a)
# Output: array([-0.9092, -0.8414,  0.  , 0.8414,  0.9092])
np.cos(a)
# Output: array([-0.4161,  0.5403,  1.  , 0.5403, -0.4161])
np.tan(a)
# Output: array([ 2.1850, -1.5574,  0.   , 1.5574, -2.1850])
np.sign(a)
# Output: array([-1, -1,  0,  1,  1])

C:\Users\AL-MOSTAFA\AppData\Local\Temp\ipykernel_14772\1094679551.py:5: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(a)


array([-1, -1,  0,  1,  1])

When you use the sin()..etc function in NumPy (or any similar function in Python), the angle is expected to be in radians, not degrees. If you provide an angle in degrees, you need to convert it to radians before applying the trigonometric function.

In [73]:
a = sin(30)
a

-0.9880316240928618

In [74]:
# Convert the angle from degrees to radians
angle_radians = np.radians(30)

# Calculate the sine of the angle in degrees
a = np.sin(angle_radians)
print(a)


0.49999999999999994


In [75]:
# Convert 30 to radians
a = np.sin(30 * np.pi / 180)
print(a)


0.49999999999999994


In [76]:
a = sin(deg2rad(45))
a.round(3)

0.707

- **Arithmetic on multiple arrays & dot product**

In [77]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.add(a, b)  
# Output: array([5, 7, 9])
np.subtract(a, b)  
# Output: array([-3, -3, -3])
np.multiply(a, b)  
# Output: array([ 4, 10, 18])
np.divide(a, b)  
# Output: array([0.25, 0.4 , 0.5 ])
np.dot(a, b)  
# Output: 32


32

- **Array comparison**

In [78]:
a = np.array([1, 2, 3])
b = np.array([4, 2, 6])

a == b  
# Output: array([False,  True, False])


array([False,  True, False])

In [79]:
np.array_equal(a, b)  
# Output: False

False

- **Accessing elements in a 1D array**

In [80]:
a = np.array([1, 2, 3, 4, 5])

a[0]  


1

In [81]:
a[1:4]  

array([2, 3, 4])

In [82]:
print(a[-1])   # last element
a[-2]   # second last element

5


4

- **Accessing elements in a 2D array**

In [83]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a[0]  

array([1, 2, 3])

In [84]:
a[0][1]  

2

In [85]:
a[1][2]

6

### **1D Array Slicing**
In NumPy, **slicing** allows you to extract specific parts of an array without having to manually loop through the elements. The slicing operation uses the syntax:

```python
array[start:stop:step]
```
Where:
- **`start`** is the index to start slicing (inclusive).
- **`stop`** is the index to end slicing (exclusive).
- **`step`** is the interval between each element to be selected.

In [86]:
arr = np.random.randint(1,10,10)
arr

array([5, 6, 2, 1, 1, 4, 1, 5, 8, 4])

In [ ]:
# Slice from index 2 to 7 (exclusive)
sliced_arr = arr[2:7]

print(sliced_arr)

[2 1 1 4 1]


In [88]:
# Slice from index 2 to 7 (exclusive), step 2

sliced_arr = arr[2:7:2] 

print(sliced_arr)

[2 1 1]


In [89]:
arr[:]  # Selects all elements

array([5, 6, 2, 1, 1, 4, 1, 5, 8, 4])

### **2D Array Slicing**

For a **2D array**, you can slice rows and columns separately. The syntax becomes:

```python
array[start_row:stop_row:step_row, start_col:stop_col:step_col]
```

- **`start_row:stop_row:step_row`**: Slices the rows.
- **`start_col:stop_col:step_col`**: Slices the columns.

In [13]:
arr = np.random.randint(1,25,(4,4))
arr

array([[21, 13, 18, 24],
       [ 1,  1,  3, 16],
       [21, 13, 12,  2],
       [ 1, 16,  7, 18]])

In [14]:
sliced_arr_2d = arr[0:3, 1:3]
print(sliced_arr_2d)

[[13 18]
 [ 1  3]
 [13 12]]


In [15]:
sliced_arr_2d = arr[:,:] # Selects all elements.
print(sliced_arr_2d)

[[21 13 18 24]
 [ 1  1  3 16]
 [21 13 12  2]
 [ 1 16  7 18]]


In [16]:
arr[3:]  # Starts at index 3 and goes to the end.

array([[ 1, 16,  7, 18]])

In [17]:
arr[:3,1:3]  # Selects elements from the beginning up to index 3 (exclusive).

array([[13, 18],
       [ 1,  3],
       [13, 12]])

In [18]:
arr

array([[21, 13, 18, 24],
       [ 1,  1,  3, 16],
       [21, 13, 12,  2],
       [ 1, 16,  7, 18]])

In [19]:
arr[::-1]  # Reverses the array.

array([[ 1, 16,  7, 18],
       [21, 13, 12,  2],
       [ 1,  1,  3, 16],
       [21, 13, 18, 24]])

**reverses the elements of the array, starting from the last element and stepping backwards to the first element.**

In [ ]:

arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Reversing rows (vertical reversal)
reversed_rows = arr[::-1, :]
print("Reversed rows:")
print(reversed_rows)

# Reversing columns (horizontal reversal)
reversed_columns = arr[:, ::-1]
print("\nReversed columns:")
print(reversed_columns)

# Reversing both rows and columns
reversed_both = arr[::-1, ::-1]
print("\nReversed both rows and columns:")
print(reversed_both)


# <img src="https://th.bing.com/th/id/OIP.2sMFUzhSVYNUT23g6ygBEQAAAA?rs=1&pid=ImgDetMain" /> <br>

In [23]:
np.array(b)

array([ 1,  5,  9,  7,  6,  3,  4,  7,  5,  1,  5, 12])

In [20]:
b = [1, 5, 9, 7, 6, 3, 4, 7, 5, 1, 5,12]
b

[1, 5, 9, 7, 6, 3, 4, 7, 5, 1, 5, 12]

In [21]:
len(b)

12

In [22]:
s = np.reshape(b, (1, 12))
s

array([[ 1,  5,  9,  7,  6,  3,  4,  7,  5,  1,  5, 12]])

In [54]:
c = np.array(b)
c

array([ 1,  5,  9,  7,  6,  3,  4,  7,  5,  1,  5, 12])

In [58]:
c = c.reshape(3, 4)

In [59]:
c

array([[ 1,  5,  9,  7],
       [ 6,  3,  4,  7],
       [ 5,  1,  5, 12]])

In [28]:
len(c)

12

In [29]:
c= c.reshape(1, 12)

**Row × Column = Size: The reshaped array s has 1 row and 12 columns, which results in a size of 12 elements (1 * 12 = 12).**

In [33]:
c.reshape(2, 6)

array([[ 1,  5,  9,  7,  6,  3],
       [ 4,  7,  5,  1,  5, 12]])

In [34]:
c.reshape(3, 4)

array([[ 1,  5,  9,  7],
       [ 6,  3,  4,  7],
       [ 5,  1,  5, 12]])

In [35]:
c.reshape(4, 3)

array([[ 1,  5,  9],
       [ 7,  6,  3],
       [ 4,  7,  5],
       [ 1,  5, 12]])

In [36]:
c.reshape(6, 2)

array([[ 1,  5],
       [ 9,  7],
       [ 6,  3],
       [ 4,  7],
       [ 5,  1],
       [ 5, 12]])

In [39]:
c.reshape(2,3,2 )

array([[[ 1,  5],
        [ 9,  7],
        [ 6,  3]],

       [[ 4,  7],
        [ 5,  1],
        [ 5, 12]]])

**Row × Column × Depth = Size**

In [53]:
c.reshape(4,3 )
c

array([[[ 1],
        [ 5],
        [ 9]],

       [[ 7],
        [ 6],
        [ 3]],

       [[ 4],
        [ 7],
        [ 5]],

       [[ 1],
        [ 5],
        [12]]])

- **The `flatten` function** returns a 1D array containing all the elements of the original array.

In [47]:
c.flatten()

array([ 1,  5,  9,  7,  6,  3,  4,  7,  5,  1,  5, 12])

In [51]:
c

array([[[ 1],
        [ 5],
        [ 9]],

       [[ 7],
        [ 6],
        [ 3]],

       [[ 4],
        [ 7],
        [ 5]],

       [[ 1],
        [ 5],
        [12]]])


- **The `ravel` function** returns a 1D array containing all the elements of the original array, but it provides a **view** of the original array (instead of a copy), meaning that changes made to the raveled array will affect the original array.

In [46]:
np.ravel(c)

array([ 1,  5,  9,  7,  6,  3,  4,  7,  5,  1,  5, 12])

| **Feature**               | **`flatten()`**                      | **`ravel()`**                        |
|---------------------------|--------------------------------------|--------------------------------------|
| **Returns**               | A copy of the original array         | A reference/view of the original array |
| **Effect of Modification**| No effect on the original array      | Modifies the original array         |
| **Memory Usage**          | Occupies additional memory (slower)  | No additional memory usage (faster) |
| **Type**                  | Method of ndarray                    | Function in NumPy library           |

So, if you need to modify the flattened array and reflect those changes in the original, 
**`ravel()`** is better. If you need a copy to keep the original array unaffected, use **`flatten()`**.


- **The `random.choice` function** returns a random element from a given array or list. It can also randomly select multiple elements, with or without replacement.

In [402]:
b

array([ 5,  9,  5,  4,  7,  1,  7,  1, 12,  6,  5,  3])

In [80]:
np.random.choice(b)

6

- **The `random.shuffle` function** randomly reorders the elements of a list in-place. It modifies the original list directly.
  
- **`b.copy()`**: When you need to preserve the original list `b` and avoid modifying it, you can create a copy using `.copy()`.

In [82]:
np.random.shuffle(b)
b

[9, 6, 7, 4, 1, 7, 12, 5, 5, 3, 1, 5]

In [83]:
z = b.copy()

np.random.shuffle(z)

print("Shuffled list:")
print(z)

print("\nOriginal list:")
print(b)

Shuffled list:
[12, 5, 4, 5, 5, 6, 7, 1, 7, 9, 3, 1]

Original list:
[9, 6, 7, 4, 1, 7, 12, 5, 5, 3, 1, 5]


In [84]:
c = np.arange(18)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [413]:
c = c.reshape(3,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [414]:
c = np.arange(18).reshape(3,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [ ]:
arr = np.arange(100).reshape(10, 2, 5)
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]]

 [[70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]]

 [[90 91 92 93 94]
  [95 96 97 98 99]]]


Breakdown:
- 10 is the number of matrices (or depth).

- 2 is the number of rows in each matrix.

- 5 is the number of columns in each row.

In [418]:
print(arr.shape)

(10, 2, 5)


**Stacking arrays** in NumPy refers to the process of joining two or more arrays along a specific axis. There are several functions available in NumPy to stack arrays:

- **`np.vstack()`**: Stacks arrays vertically (along rows).

In [85]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.vstack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]]


- **`np.hstack()`**: Stacks arrays horizontally (along columns).


In [424]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.hstack((arr1, arr2))
print(result)


[1 2 3 4 5 6]



- **`np.dstack()`**: Stacks arrays along the third axis (depth).


In [89]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2), axis=0)
print(result)


[1 2 3 4 5 6]


In [92]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2), axis=1)
print(result)


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


### Explanation:
- **1D arrays**: Concatenating along **axis 0** (the only axis for 1D arrays) simply combines the arrays into a longer 1D array.
- **2D arrays**: Concatenating along **axis 1** adds the columns of `arr2` to the columns of `arr1`.

- **`reduce`**: Performs a cumulative operation (e.g., sum or multiplication) on the array.


In [ ]:
import numpy as np
m = np.array([1, 2, 3, 4])

result = np.add.reduce(m)
print(result)  #  (1+2+3+4)


10


In [443]:
result = np.multiply.reduce(m)
print(result)  #  (1*2*3*4)


24


- **`trace`**: Computes the trace of a matrix (sum of diagonal elements).


In [452]:
q=np.arange(1,17).reshape(4,4)
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [453]:
trace_value = np.trace(q)
print(trace_value)

34


- **`det`**: Computes the determinant of a matrix.


In [454]:
det_value = np.linalg.det(q)
print(det_value)


0.0


- **`split`**: Splits an array into sub-arrays at specified indices.

In [94]:
a = np.array([1, 2, 3, 4, 5, 6])

split_result = np.split(a, (0, 4))
print(split_result)

[array([], dtype=int32), array([1, 2, 3, 4]), array([5, 6])]


In [95]:
len(split_result)


3

In [ ]:
a1, a2, a3 = split(a, (0, 4))
print(a1)
print(a2)
print(a3)

[1]
[2 3 4]
[5 6]


### Explanation:
- **`np.split(a, (0, 4))`** divides the array `a` into parts based on the indices you provided. The result will have 3 parts:
  - One part before index 0 (which is an empty array).
  - One part from index 0 to index 4.
  - One part from index 4 to the end.

### Contact Me 📞✉️
### Ahmed ElSany 

Feel free to reach out to me anytime!  

- 📱 **Whatsapp:** 01008141749

- 📧 **LinkedIn:** https://www.linkedin.com/in/ahmed-elsany-0a588a223/

- 📧 **Facebook:** https://www.facebook.com/profile.php?id=100009780577339


### Don't Stop , It's Just Begininning